In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/periibrahimli/dddhhh/owid-covid-data.csv
/kaggle/input/datasets/periibrahimli/covid-19-data/owid-covid-data.csv

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('/kaggle/input/datasets/periibrahimli/dddhhh/owid-covid-data.csv')

In [4]:
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2/24/2020,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2/25/2020,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2/26/2020,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2/27/2020,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2/28/2020,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166321,ZWE,Africa,Zimbabwe,3/1/2022,236871.0,491.0,413.000,5395.0,0.0,1.000,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
166322,ZWE,Africa,Zimbabwe,3/2/2022,237503.0,632.0,416.286,5396.0,1.0,1.143,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
166323,ZWE,Africa,Zimbabwe,3/3/2022,237503.0,0.0,362.286,5396.0,0.0,0.857,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
166324,ZWE,Africa,Zimbabwe,3/4/2022,238739.0,1236.0,467.429,5397.0,1.0,0.714,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
166325,ZWE,Africa,Zimbabwe,3/5/2022,239019.0,280.0,459.429,5397.0,0.0,0.571,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [5]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166326 entries, 0 to 166325
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    166326 non-null  object
 1   continent                                   156370 non-null  object
 2   location                                    166326 non-null  object
 3   date                                        166326 non-null  object
 4   total_cases                                 163293 non-null  float64
 5   new_cases                                   163133 non-null  float64
 6   new_cases_smoothed                          161150 non-null  float64
 7   total_deaths                                145451 non-null  float64
 8   new_deaths                                  145487 non-null  float64
 9   new_deaths_smoothed                         143390 non-null  float64
 10  total_cases_per_million                     162535 non-null  float64
 11  new_cases_per_million                       162375 non-null  float64
 12  new_cases_smoothed_per_million              160398 non-null  float64
 13  total_deaths_per_million                    144706 non-null  float64
 14  new_deaths_per_million                      144742 non-null  float64
 15  new_deaths_smoothed_per_million             142651 non-null  float64
 16  reproduction_rate                           125820 non-null  float64
 17  icu_patients                                23463 non-null   float64
 18  icu_patients_per_million                    23463 non-null   float64
 19  hosp_patients                               24617 non-null   float64
 20  hosp_patients_per_million                   24617 non-null   float64
 21  weekly_icu_admissions                       5433 non-null    float64
 22  weekly_icu_admissions_per_million           5433 non-null    float64
 23  weekly_hosp_admissions                      10923 non-null   float64
 24  weekly_hosp_admissions_per_million          10923 non-null   float64
 25  new_tests                                   67317 non-null   float64
 26  total_tests                                 69255 non-null   float64
 27  total_tests_per_thousand                    69255 non-null   float64
 28  new_tests_per_thousand                      67317 non-null   float64
 29  new_tests_smoothed                          84035 non-null   float64
 30  new_tests_smoothed_per_thousand             84035 non-null   float64
 31  positive_rate                               78655 non-null   float64
 32  tests_per_case                              78084 non-null   float64
 33  tests_units                                 86386 non-null   object
 34  total_vaccinations                          45194 non-null   float64
 35  people_vaccinated                           42987 non-null   float64
 36  people_fully_vaccinated                     40241 non-null   float64
 37  total_boosters                              17539 non-null   float64
 38  new_vaccinations                            37447 non-null   float64
 39  new_vaccinations_smoothed                   84398 non-null   float64
 40  total_vaccinations_per_hundred              45194 non-null   float64
 41  people_vaccinated_per_hundred               42987 non-null   float64
 42  people_fully_vaccinated_per_hundred         40241 non-null   float64
 43  total_boosters_per_hundred                  17539 non-null   float64
 44  new_vaccinations_smoothed_per_million       84398 non-null   float64
 45  new_people_vaccinated_smoothed              83088 non-null   float64
 46  new_people_vaccinated_smoothed_per_hundred  83088 non-null   float64
 47  stringency_index                            130072 non-null  float64
 48  population                                  165251 non-null  float64
 49  population_density                          147928 non-null  float64
 50  median_age                                  137831 non-null  float64
 51  aged_65_older                               136337 non-null  float64
 52  aged_70_older                               137092 non-null  float64
 53  gdp_per_capita                              138504 non-null  float64
 54  extreme_poverty                             91215 non-null   float64
 55  cardiovasc_death_rate                       136778 non-null  float64
 56  diabetes_prevalence                         143949 non-null  float64
 57  female_smokers                              106050 non-null  float64
 58  male_smokers                                104595 non-null  float64
 59  handwashing_facilities                      68569 non-null   float64
 60  hospital_beds_per_thousand                  123664 non-null  float64
 61  life_expectancy                             155268 non-null  float64
 62  human_development_index                     136253 non-null  float64
 63  excess_mortality_cumulative_absolute        5696 non-null    float64
 64  excess_mortality_cumulative                 5696 non-null    float64
 65  excess_mortality                            5696 non-null    float64
 66  excess_mortality_cumulative_per_million     5696 non-null    float64
dtypes: float64(62), object(5)
memory usage: 85.0+ MB

In [6]:
df['date']=pd.to_datetime(df['date'])

In [7]:
df.sort_values(by='date')

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
98000,MEX,North America,Mexico,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,6.9,21.4,87.847,1.380,75.05,0.779,NaN,NaN,NaN,NaN
5854,ARG,South America,Argentina,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,16.2,27.7,NaN,5.000,76.67,0.845,NaN,NaN,NaN,NaN
98001,MEX,North America,Mexico,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,...,6.9,21.4,87.847,1.380,75.05,0.779,NaN,NaN,NaN,NaN
5855,ARG,South America,Argentina,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,...,16.2,27.7,NaN,5.000,76.67,0.845,NaN,NaN,NaN,NaN
98002,MEX,North America,Mexico,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,...,6.9,21.4,87.847,1.380,75.05,0.779,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132758,SRB,Europe,Serbia,2022-03-05,1923977.0,2146.0,2547.857,15405.0,30.0,35.714,...,37.7,40.2,97.719,5.609,76.00,0.806,NaN,NaN,NaN,NaN
105733,NAM,Africa,Namibia,2022-03-05,157324.0,13.0,18.714,4013.0,0.0,0.857,...,9.7,34.2,44.600,NaN,63.71,0.646,NaN,NaN,NaN,NaN
8907,OWID_ASI,NaN,Asia,2022-03-05,120758420.0,687653.0,662127.429,1363608.0,1832.0,1948.429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146926,TWN,Asia,Taiwan,2022-03-05,20797.0,80.0,60.571,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
166325,ZWE,Africa,Zimbabwe,2022-03-05,239019.0,280.0,459.429,5397.0,0.0,0.571,...,1.6,30.7,36.791,1.700,61.49,0.571,NaN,NaN,NaN,NaN

In [8]:
df.isnull().sum()

iso_code                                        0
continent                                    9956
location                                        0
date                                            0
total_cases                                  3033
                                            ...
human_development_index                     30073
excess_mortality_cumulative_absolute       160630
excess_mortality_cumulative                160630
excess_mortality                           160630
excess_mortality_cumulative_per_million    160630
Length: 67, dtype: int64

In [9]:
df.fillna(0)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,0.000,0.0,0.0,0.000,...,0.0,0.0,37.746,0.5,64.83,0.511,0.0,0.0,0.0,0.0
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,0.000,0.0,0.0,0.000,...,0.0,0.0,37.746,0.5,64.83,0.511,0.0,0.0,0.0,0.0
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,0.000,0.0,0.0,0.000,...,0.0,0.0,37.746,0.5,64.83,0.511,0.0,0.0,0.0,0.0
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,0.000,0.0,0.0,0.000,...,0.0,0.0,37.746,0.5,64.83,0.511,0.0,0.0,0.0,0.0
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,0.000,0.0,0.0,0.000,...,0.0,0.0,37.746,0.5,64.83,0.511,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166321,ZWE,Africa,Zimbabwe,2022-03-01,236871.0,491.0,413.000,5395.0,0.0,1.000,...,1.6,30.7,36.791,1.7,61.49,0.571,0.0,0.0,0.0,0.0
166322,ZWE,Africa,Zimbabwe,2022-03-02,237503.0,632.0,416.286,5396.0,1.0,1.143,...,1.6,30.7,36.791,1.7,61.49,0.571,0.0,0.0,0.0,0.0
166323,ZWE,Africa,Zimbabwe,2022-03-03,237503.0,0.0,362.286,5396.0,0.0,0.857,...,1.6,30.7,36.791,1.7,61.49,0.571,0.0,0.0,0.0,0.0
166324,ZWE,Africa,Zimbabwe,2022-03-04,238739.0,1236.0,467.429,5397.0,1.0,0.714,...,1.6,30.7,36.791,1.7,61.49,0.571,0.0,0.0,0.0,0.0
166325,ZWE,Africa,Zimbabwe,2022-03-05,239019.0,280.0,459.429,5397.0,0.0,0.571,...,1.6,30.7,36.791,1.7,61.49,0.571,0.0,0.0,0.0,0.0

In [10]:
missing_value_percentage = df.isnull().sum() / len(df) * 100
missing_value_percentage

iso_code                                    0.000000
continent                                   5.985835
location                                    0.000000
date                                        0.000000
total_cases                                 1.823527
                                             ...
human_development_index                    18.080757
excess_mortality_cumulative_absolute       96.575400
excess_mortality_cumulative                96.575400
excess_mortality                           96.575400
excess_mortality_cumulative_per_million    96.575400
Length: 67, dtype: float64

In [11]:
import numpy as np

df["z_score"] = (df["new_cases"] - df["new_cases"].mean()) / df["new_cases"].std()

outliers = df[np.abs(df["z_score"]) > 3]

print(outliers[["date", "new_cases", "z_score"]])

             date  new_cases    z_score
8575   2021-04-07   268496.0   3.043200
8576   2021-04-08   279766.0   3.176690
8577   2021-04-09   293201.0   3.335823
8578   2021-04-10   289567.0   3.292780
8579   2021-04-11   305951.0   3.486843
...           ...        ...        ...
164192 2022-03-01  1536867.0  18.066668
164193 2022-03-02  1651452.0  19.423892
164194 2022-03-03  1887465.0  22.219395
164195 2022-03-04  1704138.0  20.047942
164196 2022-03-05  1361810.0  15.993171

[1510 rows x 3 columns]

In [12]:
df["z_score"] = (df["new_deaths"] - df["new_deaths"].mean()) / df["new_deaths"].std()

outliers = df[np.abs(df["z_score"]) > 3]

print(outliers[["date", "new_deaths", "z_score"]])

             date  new_deaths    z_score
6128   2020-10-01      3351.0   3.820796
8558   2021-03-21      3180.0   3.615329
8583   2021-04-15      2693.0   3.030170
8584   2021-04-16      2789.0   3.145519
8585   2021-04-17      2921.0   3.304125
...           ...         ...        ...
164192 2022-03-01      8069.0   9.489757
164193 2022-03-02      7945.0   9.340763
164194 2022-03-03      8384.0   9.868248
164195 2022-03-04      8771.0  10.333252
164196 2022-03-05      5443.0   6.334460

[2674 rows x 3 columns]

In [13]:
df['date'].duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
166321     True
166322     True
166323     True
166324     True
166325     True
Name: date, Length: 166326, dtype: bool

In [14]:
df['location'].duplicated()

0         False
1          True
2          True
3          True
4          True
          ...
166321     True
166322     True
166323     True
166324     True
166325     True
Name: location, Length: 166326, dtype: bool

In [15]:
df = df.dropna(subset=['continent'], how="any")
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million,z_score
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166321,ZWE,Africa,Zimbabwe,2022-03-01,236871.0,491.0,413.000,5395.0,0.0,1.000,...,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN,-0.205632
166322,ZWE,Africa,Zimbabwe,2022-03-02,237503.0,632.0,416.286,5396.0,1.0,1.143,...,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN,-0.204430
166323,ZWE,Africa,Zimbabwe,2022-03-03,237503.0,0.0,362.286,5396.0,0.0,0.857,...,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN,-0.205632
166324,ZWE,Africa,Zimbabwe,2022-03-04,238739.0,1236.0,467.429,5397.0,1.0,0.714,...,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN,-0.204430
166325,ZWE,Africa,Zimbabwe,2022-03-05,239019.0,280.0,459.429,5397.0,0.0,0.571,...,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN,-0.205632

In [16]:
--bu hisseye kimi biz datanı təmizlədik və ümumi sətir və sütunlar haqqında 
--məlumatlandıq.

SyntaxError: invalid syntax (296901921.py, line 1)

In [ ]:
top_country = df.groupby("location")["new_cases"].sum().sort_values(ascending=False).head(10)
print(top_country)

In [ ]:
df["death_rate"] = (df["total_deaths"]/df["total_cases"]) * 100
df.groupby('location')['death_rate'].max().sort_values(ascending=False).head(10)

In [ ]:
df.groupby('continent')['total_cases'].mean()

In [ ]:
df.groupby('continent')['total_deaths'].mean()

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(12,8))
plt.plot(df["date"], df["new_cases_smoothed"], color="blue")
plt.xlabel("Date")
plt.ylabel("Smoothed New Cases")
plt.title("Pandemic Trend (Smoothed New Cases)")
plt.grid(True)
plt.show()

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(12,8))
plt.plot(df["new_cases"], df["people_vaccinated"], color="blue")

plt.xlabel("New Cases")
plt.ylabel("Vaccination Count")
plt.title("Vaccination vs New Cases")
plt.grid(True)

plt.show()

biz burada görə bilərik ki vaksinləşmə artdıqca ölüm sayı artmayıb

In [ ]:
clean_df = df[["people_vaccinated", "new_cases"]].dropna()

corr = clean_df["people_vaccinated"].corr(clean_df["new_cases"])
print("Correlation:", corr)

In [ ]:
clean_df = df[["stringency_index", "new_cases"]].dropna()

corr = clean_df["stringency_index"].corr(clean_df["new_cases"])
print("Correlation:", corr)

In [ ]:
df.groupby('location')[['hospital_beds_per_thousand','total_deaths']].sum()

In [ ]:
grouped = df.groupby('location')[['hospital_beds_per_thousand','total_deaths']].sum().dropna()

plt.figure(figsize=(10,6))
plt.scatter(grouped['hospital_beds_per_thousand'], grouped['total_deaths'])

plt.xlabel("Hospital Beds per Thousand")
plt.ylabel("Total Deaths")
plt.title("Beds vs Deaths")

plt.grid(True)
plt.show()

buradan görə bilərikki saglamlıq sistemi güclü olan ölkələrdə ölüm sayı daha azdır

In [ ]:
grouped = df.groupby("aged_65_older")["death_rate"].sum()
print(grouped)

Hansı qitə pandemiyanı ən yaxşı idarə edib?
oceania ən yaxşı idarə edənlərdəndir çünki digər ölkələrə nisbətən ən az ölüm ortalaması oradadır.Ən kəskin ölüm olan qitə isə south americadır

Vakansiyalar nə dərəcədə effektiv olub?
virusun yayılmasının qarşısını alıb və ölümün artmamasına səbəb olub